#!/usr/bin/env sh
# shellcheck disable=SC3043,SC2034,SC1090
# shelx - posix scripting template
# MIT License - Copyright (c) 2024-2026 Benexl

# ==============================================================================
# META
# ==============================================================================
readonly CLI_NAME="${SHELX_APP_NAME:-shelx}"
readonly CLI_ARGS="$*"
readonly CLI_APP_NAME="${SHELX_APP_NAME:-shelx}"
readonly CLI_VERSION="0.8.0"
readonly CLI_AUTHOR="Benexl"
readonly CLI_REPO_URL="https://github.com/Benexl/shelx"
readonly CLI_URL="https://raw.githubusercontent.com/Benexl/shelx/refs/heads/master/shelx"

# ==============================================================================
# SETUP
# ==============================================================================
# shellcheck disable=2155
readonly CLI_START_TIME="$(date +%s)"

_dep_ch() {
  command -v "$1" >/dev/null 2>&1
}

# ==============================================================================
# SETUP ENVIRONMENT
# ==============================================================================
if [ -n "$BASH_VERSION" ]; then
  readonly CLI_SHELL="bash"
elif [ -n "$ZSH_VERSION" ]; then
  readonly CLI_SHELL="zsh"
elif [ -n "$KSH_VERSION" ]; then
  readonly CLI_SHELL="ksh"
else
  readonly CLI_SHELL="sh"
fi

if ! _dep_ch local; then
  eval 'local() { unset -v $1; }'
fi

if _dep_ch realpath; then
  # shellcheck disable=SC2155
  readonly CLI_DIR="$(dirname "$(realpath "$0")")"
else
  # shellcheck disable=SC2155
  readonly CLI_DIR="$(cd "$(dirname "$0")" && pwd -P)"
fi

readonly CLI_PATH="$CLI_DIR/$CLI_NAME"

if [ "$CLI_SHELL" = "zsh" ]; then
  setopt shwordsplit
fi

case "$(uname -a)" in
*ndroid*) readonly CLI_PLATFORM="android" ;;
*Darwin*) readonly CLI_PLATFORM="mac" ;;
*WSL* | *microsoft* | *Microsoft*) readonly CLI_PLATFORM="linux" ;;
*MINGW* | *MSYS* | *CYGWIN*) readonly CLI_PLATFORM="windows" ;;
*) readonly CLI_PLATFORM="linux" ;;
esac

if [ -t 1 ]; then
  readonly CLI_IS_TERMINAL=true
else
  readonly CLI_IS_TERMINAL=false
fi

if [ "$COLORTERM" = "truecolor" ] || [ "$COLORTERM" = "24bit" ]; then
  readonly CLI_SUPPORTS_TRUE_COLOR=true
else
  readonly CLI_SUPPORTS_TRUE_COLOR=false
fi

export SHELL="sh"

# ==============================================================================
# SETUP PATHS
# ==============================================================================
XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"
XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"

readonly CLI_CONFIG_DIR="$XDG_CONFIG_HOME/$CLI_APP_NAME"

readonly CLI_CACHE_DIR="$XDG_CACHE_HOME/$CLI_APP_NAME"

readonly CLI_STATE_DIR="$CLI_CACHE_DIR/state"
readonly CLI_CURRENT_STATE_DIR="$CLI_STATE_DIR/${CLI_START_TIME}-$$"

readonly CLI_PREVIEW_DIR="$CLI_CACHE_DIR/previews"
readonly CLI_PREVIEW_IMGS_DIR="$CLI_PREVIEW_DIR/images"
readonly CLI_PREVIEW_SCRIPTS_DIR="$CLI_PREVIEW_DIR/text"
readonly CLI_FZF_PREVIEW_SCRIPT="$CLI_PREVIEW_SCRIPTS_DIR/fzf-preview.sh"

readonly CLI_CONFIG_FILE="$CLI_CONFIG_DIR/config"
readonly CLI_DEFAULT_THEME_FILE="$CLI_EXTENSIONS_THEMES_DIR/default.theme"
readonly CLI_DEFAULT_LANG_FILE="$CLI_EXTENSIONS_LANGS_DIR/default.lang"
readonly CLI_RECENT_FILE="$CLI_CONFIG_DIR/recent.json"
readonly CLI_SEARCH_HISTORY_FILE="$CLI_CACHE_DIR/search-history.txt"

mkdir -p \
  "$CLI_CONFIG_DIR" \
  "$CLI_CURRENT_STATE_DIR" \
  "$CLI_PREVIEW_IMGS_DIR" \
  "$CLI_PREVIEW_SCRIPTS_DIR"

# ==============================================================================
# CONFIGURATION & ENVIRONMENT
# ==============================================================================
__load_default_config() {
  :
}

__load_env_config() {
  :
}

__load_default_lang() {
  :
}

__load_default_theme() {
  :
}

__post_config_load() {
  :
}

_print_config() {
  :
}

_load_config() {
  :
}

# ==============================================================================
# CORE: utilities
# ==============================================================================
_util_terminal_exec() {
  local term
  local old_ifs
  local cmd
  cmd="$*"
  old_ifs="$IFS"

  if ! $CLI_IS_TERMINAL; then
    if [ -n "$CONFIG_TERMINAL_EXEC" ]; then
      term="$CONFIG_TERMINAL_EXEC"
    elif _dep_ch kitty; then
      term="kitty --exec"
    elif _dep_ch alacritty; then
      term="alacritty --command"
    else
      ui_notify_error "$TXT_NO_TERMINAL_EXEC"
      return 1
    fi
    IFS=" "
    # shellcheck disable=SC2086
    $term $cmd
    IFS="$old_ifs"
    return
  fi
  IFS=" "
  $cmd
  IFS="$old_ifs"
}

_util_open() {
  local target
  local converted_target
  target="$1"

  if _dep_ch open; then
    open "$target" || return 1
    return 0
  elif _dep_ch xdg-open; then
    xdg-open "$target" || return 1
    return 0
  elif _dep_ch wslview; then
    wslview "$target" || return 1
    return 0
  elif _dep_ch cmd.exe; then
    converted_target="$target"

    case "$target" in
    http://* | https://* | ftp://* | ftps://* | mailto:*) ;;
    *)
      if _dep_ch cygpath; then
        converted_target="$(cygpath -w "$target" 2>/dev/null || printf "%s" "$target")"
      elif _dep_ch wslpath; then
        converted_target="$(wslpath -w "$target" 2>/dev/null || printf "%s" "$target")"
      fi
      ;;
    esac

    cmd.exe /C start "" "$converted_target" >/dev/null 2>&1 || return 1
    return 0
  else
    return 1
  fi
}

_util_file_edit() {
  local file_path
  file_path="$1"

  if _dep_ch "$CONFIG_EDITOR"; then
    _util_terminal_exec "$CONFIG_EDITOR" "$file_path"
  elif _dep_ch "$EDITOR"; then
    _util_terminal_exec "$EDITOR" "$file_path"
  elif ! _util_open "$file_path"; then
    ui_notify_warning "$TXT_EDITOR_NOT_FOUND"
  fi
}

_util_generate_hash() {
  local input

  if [ -n "$1" ]; then
    input="$1"
  else
    input=$(cat)
  fi

  if _dep_ch sha256sum; then
    printf "%s" "$input" | sha256sum | awk '{print $1}'
  elif _dep_ch shasum; then
    printf "%s" "$input" | shasum -a 256 | awk '{print $1}'
  elif _dep_ch sha256; then
    printf "%s" "$input" | sha256 | awk '{print $1}'
  elif _dep_ch openssl; then
    printf "%s" "$input" | openssl dgst -sha256 | awk '{print $2}'
  else
    printf "%s" "$input" | base64 | tr '/+' '_-' | tr -d '\n'
  fi
}

_util_menu_sort() {
  # TODO: shift to using awk
  local options_to_sort
  local options_to_sort_copy
  local sort
  local i
  i=0
  options_to_sort="$1"
  sort="$2"

  for option in $(printf '%s' "$options_to_sort" | tr ' ' '-'); do
    i=$((i + 1))
    if [ -z "$options_to_sort_copy" ]; then
      options_to_sort_copy="$i:$option"
    else
      options_to_sort_copy="$options_to_sort_copy\n$i:$option"
    fi
  done

  for order in $(printf '%s' "$sort" | tr ',' '\n'); do
    printf "$options_to_sort_copy" | grep "^$order:" | sed "s/$order://g" | tr '-' ' '
  done
}

_util_byebye() {
  printf '%s %s\n' "$TXT_BYEBYE" "$USER"
  exit
}
# ==============================================================================
# CORE UI: notify
# ==============================================================================
__ui_notify_terminal() {
  #TODO: finish implementation
  case "$1" in
  info) printf '%s\n' "$2" >&2 && sleep "$CONFIG_NOTIFICATION_DURATION" ;;
  warning) printf '%s\n' "$2" >&2 && sleep "$CONFIG_NOTIFICATION_DURATION" ;;
  error) printf '%s\n' "$2" >&2 && sleep "$CONFIG_NOTIFICATION_DURATION" ;;
  critical) printf '%s\n' "$2" >&2 && exit 1 ;;
  *) printf '%s\n' "$2" >&2 && sleep "$CONFIG_NOTIFICATION_DURATION" ;;
  esac

}

__ui_notify_non_terminal() {
  #TODO: finish implementation
  case "$1" in
  info) notify-send "$2" ;;
  warning) notify-send "$2" ;;
  error) notify-send "$2" ;;
  critical) notify-send "$2" && exit 1 ;;
  esac
}

_ui_notify() {
  if $CLI_IS_TERMINAL; then
    __ui_notify_terminal info "$1"
  else
    __ui_notify_non_terminal info "$1"
  fi
}

_ui_notify_warning() {
  if $CLI_IS_TERMINAL; then
    __ui_notify_terminal warning "$1"
  else
    __ui_notify_non_terminal warning "$1"
  fi
}

_ui_notify_error() {
  if $CLI_IS_TERMINAL; then
    __ui_notify_terminal error "$1"
  else
    __ui_notify_non_terminal error "$1"
  fi
}

_ui_notify_critical() {
  if $CLI_IS_TERMINAL; then
    __ui_notify_terminal critical "$1"
  else
    __ui_notify_non_terminal critical "$1"
  fi
}

ui_notify() {
  _ui_notify "$@"
}

ui_notify_warning() {
  _ui_notify_warning "$@"
}

ui_notify_error() {
  _ui_notify_error "$@"
}

ui_notify_critical() {
  _ui_notify_critical "$@"
}

# ==============================================================================
# CORE UI: launcher
# ==============================================================================
__ui_fzf_launcher() {
  local custom_opts
  local multi_select
  multi_select="$2"

  [ "$multi_select" = "multi" ] && custom_opts="--multi"
  [ -n "$CONFIG_FZF_HEADER" ] && custom_opts="$custom_opts --header-first --header=$CONFIG_FZF_HEADER"

  # TODO: is there a better way to do this
  local old_ifs
  old_ifs="$IFS"
  IFS=" "

  # shellcheck disable=SC2086
  fzf --prompt="${1}: " $custom_opts

  IFS="$old_ifs"
}

__ui_rofi_launcher() {
  ! [ -s "$CONFIG_ROFI_THEME_MAIN" ] && ui_notify_critical "$TXT_ROFI_NOT_CONFIGURED: where CONFIG_ROFI_THEME_MAIN=\"$CONFIG_ROFI_THEME_MAIN\""
  local selection
  local custom_opts
  local multi_select
  local line

  multi_select="$2"
  [ "$multi_select" = "multi" ] && custom_opts="-multi-select"

  # shellcheck disable=SC2086
  selection=$(
    sed -E "s/$THEME_ESC(\[[0-9;]*[a-zA-Z]|\(B)//g" |
      rofi -no-config -theme "$CONFIG_ROFI_THEME_MAIN" -dmenu -i $custom_opts -p "$1"
  )
  printf '%s' "$selection"
}

_ui_launcher() {
  case "$CONFIG_LAUNCHER" in
  rofi) __ui_rofi_launcher "$@" ;;
  fzf) __ui_fzf_launcher "$@" ;;
  *) ui_notify_critical "$TXT_LAUNCHER_UNKNOWN: $CONFIG_LAUNCHER" ;;
  esac
}

ui_launcher() {
  _ui_launcher "$@"
}

# ==============================================================================
# CORE UI: launcher with preview
# ==============================================================================
__ui_fzf_launcher_with_preview() {
  local custom_opts
  local multi_select
  local preview_script

  preview_script="\
TXT_PREVIEW_INSTALL_VIEWER='$TXT_PREVIEW_INSTALL_VIEWER'
CONFIG_IMAGE_RENDERER='$CONFIG_IMAGE_RENDERER'
CLI_PLATFORM='$CLI_PLATFORM'
THEME_FZF_PREVIEW_DIVIDER='$THEME_FZF_PREVIEW_DIVIDER'
preview_script_path='{1}'
[ -s \"\$preview_script_path\" ] && . \"\$preview_script_path\"\
"

  multi_select="$2"
  [ "$multi_select" = "multi" ] && custom_opts="--multi"
  [ -n "$CONFIG_FZF_HEADER" ] && custom_opts="$custom_opts --header-first --header=$CONFIG_FZF_HEADER"

  # TODO: is there a better way to do this
  local old_ifs
  old_ifs="$IFS"
  IFS=" "

  # shellcheck disable=SC2086
  fzf --prompt="${1}: " --delimiter '|' --with-nth "{2..}" --accept-nth "{2..}" --preview="$preview_script" $custom_opts

  IFS="$old_ifs"
}

__ui_rofi_launcher_with_preview() {
  ! [ -s "$CONFIG_ROFI_THEME_PREVIEW" ] && ui_notify_critical "$TXT_ROFI_NOT_CONFIGURED: where CONFIG_ROFI_THEME_PREVIEW=\"$CONFIG_ROFI_THEME_PREVIEW\""
  local selection
  local custom_opts
  local multi_select
  local line

  multi_select="$2"
  [ "$multi_select" = "multi" ] && custom_opts="-multi-select"

  # shellcheck disable=SC2086
  selection=$(
    sed -E "s/$THEME_ESC(\[[0-9;]*[a-zA-Z]|\(B)//g" |
      rofi -no-config -theme "$CONFIG_ROFI_THEME_PREVIEW" -dmenu -i $custom_opts -p "$1"
  )
  printf '%s' "$selection"
}

_ui_launcher_with_preview() {
  if [ "$CONFIG_ENABLE_PREVIEW" = "true" ]; then
    case "$CONFIG_LAUNCHER" in
    rofi) __ui_rofi_launcher_with_preview "$@" ;;
    fzf) __ui_fzf_launcher_with_preview "$@" ;;
    *) ui_notify_critical "$TXT_LAUNCHER_UNKNOWN: $CONFIG_LAUNCHER" ;;
    esac
  else
    ui_launcher "$@" && return
  fi
}

ui_launcher_with_preview() {
  _ui_launcher_with_preview "$@"
}

# ==============================================================================
# CORE UI: prompt
# ==============================================================================
__ui_default_prompt() {
  local header
  local value
  header="$2"

  if _dep_ch gum; then
    gum input --header "$header" --prompt "$1: "
  else
    printf "%s\n" "$header" >/dev/stderr
    printf "%s: " "$1" >/dev/stderr
    read -r value
    printf "%s" "$value"
  fi
}

__ui_rofi_prompt() {
  local default
  local filter

  if [ -p /dev/stdin ]; then
    default="$(cat 2>/dev/null)"
    filter='-filter'
  fi

  [ -s "$CONFIG_ROFI_THEME_PROMPT" ] ||
    ui_notify_critical "Rofi prompt theme not set: $CONFIG_ROFI_THEME_PROMPT"

  # NOTE: It doesnt look pretty so disabling it
  if [ -n "$2" ] && false; then
    # shellcheck disable=SC2086
    rofi -no-config -theme "$CONFIG_ROFI_THEME_PROMPT" "$filter" "$default" -dmenu -p "$1" -mesg "$2"
  else
    # shellcheck disable=SC2086
    rofi -no-config -theme "$CONFIG_ROFI_THEME_PROMPT" "$filter" "$default" -dmenu -p "$1"
  fi
}

_ui_prompt() {
  case "$CONFIG_LAUNCHER" in
  rofi) __ui_rofi_prompt "$@" ;;
  *) __ui_default_prompt "$@" ;;
  esac
}

ui_prompt() {
  _ui_prompt "$@"
}

# ==============================================================================
# CORE UI: confirm
# ==============================================================================
_ui_default_confirm() {
  local yes
  local no
  local default
  local default_index

  yes="${3:-$TXT_YES}"
  no="${4:-$TXT_NO}"
  default="${2:-$no}"

  if [ "$default" = "$yes" ]; then
    default_index=1
  else
    default_index=0
  fi

  if _dep_ch gum; then
    gum confirm "$1" --default="$default_index" --affirmative="$yes" --negative="$no"
  else
    printf "%s ($yes/$no; $TXT_CONFIRM_DEFAULT: $default): " "$1" >/dev/stderr
    read -r CONFIRMED
    case "$CONFIRMED" in
    "$yes")
      return 0
      ;;
    "$no")
      return 1
      ;;
    *)
      if [ "$default" = "$yes" ]; then
        return 0
      else
        return 1
      fi
      ;;
    esac
  fi
}

_ui_rofi_confirm() {
  ! [ -s "$CONFIG_ROFI_THEME_CONFIRM" ] && ui_notify_critical "$TXT_ROFI_NOT_CONFIGURED: where CONFIG_ROFI_THEME_CONFIRM=\"$CONFIG_ROFI_THEME_CONFIRM\""
  local yes
  local no
  local default
  local default_index
  local selection

  yes="${3:-$TXT_YES}"
  no="${4:-$TXT_NO}"
  default="${2:-$no}"

  if [ "$default" = "$yes" ]; then
    default_index=0
  else
    default_index=1
  fi

  selection="$(printf "%s\n%s" "$yes" "$no" |
    rofi -no-config -theme "$CONFIG_ROFI_THEME_CONFIRM" -dmenu -i -p "$1" -selected-row "$default_index")"
  [ "$selection" = "$yes" ] && return 0 || return 1
}

_ui_confirm() {
  case "$CONFIG_LAUNCHER" in
  rofi) _ui_rofi_confirm "$@" ;;
  *) _ui_default_confirm "$@" ;;
  esac
}

ui_confirm() {
  _ui_confirm "$@"
}

# ==============================================================================
# CORE UI: pager
# ==============================================================================
__ui_default_pager() {
  if _dep_ch bat; then
    bat --paging=always --theme=TwoDark --color=always
  elif _dep_ch gum; then
    gum pager
  elif _dep_ch less; then
    less -R
  else
    more
  fi
}

__ui_rofi_pager() {
  ! [ -s "$CONFIG_ROFI_THEME_PAGER" ] && ui_notify_critical "$TXT_ROFI_NOT_CONFIGURED: where CONFIG_ROFI_THEME_PAGER=\"$CONFIG_ROFI_THEME_PAGER\""

  rofi -no-config -theme "$CONFIG_ROFI_THEME_PAGER" -dmenu -i -mesg "$TXT_ROFI_PAGER_MESSAGE" -p "$TXT_ROFI_PAGER_PROMPT"
}

_ui_pager() {
  case "$CONFIG_LAUNCHER" in
  rofi) __ui_rofi_pager ;;
  *) __ui_default_pager ;;
  esac
}

ui_pager() {
  _ui_pager
}

# ==============================================================================
# CORE UI: loader
# ==============================================================================
__ui_default_loader() {
  local cmd
  cmd="$*"

  if _dep_ch gum; then
    # shellcheck disable=SC2086
    gum spin --show-output -- $cmd
  else
    printf '%s\n' "$TXT_LOADING" >/dev/stderr
    $cmd
  fi

}

__ui_rofi_loader() {
  local cmd
  cmd="$*"

  ui_notify "$TXT_LOADING"
  $cmd
}

_ui_loader() {
  case "$CONFIG_LAUNCHER" in
  rofi) __ui_rofi_loader "$@" ;;
  *) __ui_default_loader "$@" ;;
  esac
}

ui_load() {
  _ui_loader "$@"
}

# ==============================================================================
# Previews
# ==============================================================================
__preview_fzf_create_shared_script() {
  if ! [ -s "$CLI_FZF_PREVIEW_SCRIPT" ]; then
    cat <<'EOF' >"$CLI_FZF_PREVIEW_SCRIPT"
#!/usr/bin/env sh
# ==============================================================================
# Shared script for fzf previews
# ==============================================================================

draw_divider() {
  ll=1
  while [ $ll -le $FZF_PREVIEW_COLUMNS ];do printf "${THEME_FZF_PREVIEW_DIVIDER}─${THEME_RESET}" ;ll=$(( ll + 1 ));done;
  echo
}

fzf_preview() {
  file=$1

  dim=${FZF_PREVIEW_COLUMNS}x${FZF_PREVIEW_LINES}
  if [ "$dim" = "x" ]; then
    dim=$(stty size </dev/tty | awk "{print \$2 \"x\" \$1}")
  fi
  if ! [ "$CONFIG_IMAGE_RENDERER" = "icat" ] && [ -z "$KITTY_WINDOW_ID" ] && [ "$((FZF_PREVIEW_TOP + FZF_PREVIEW_LINES))" -eq "$(stty size </dev/tty | awk "{print \$1}")" ]; then
    dim=${FZF_PREVIEW_COLUMNS}x$((FZF_PREVIEW_LINES - 1))
  fi

  if [ "$CONFIG_IMAGE_RENDERER" = "icat" ] && [ -z "$GHOSTTY_BIN_DIR" ]; then
    if command -v kitten >/dev/null 2>&1; then
      kitten icat --clear --transfer-mode=memory --unicode-placeholder --stdin=no --place="$dim@0x0" "$file" | sed "\$d" | sed "$(printf "\$s/\$/\033[m/")"
    elif command -v icat >/dev/null 2>&1; then
      icat --clear --transfer-mode=memory --unicode-placeholder --stdin=no --place="$dim@0x0" "$file" | sed "\$d" | sed "$(printf "\$s/\$/\033[m/")"
    else
      kitty icat --clear --transfer-mode=memory --unicode-placeholder --stdin=no --place="$dim@0x0" "$file" | sed "\$d" | sed "$(printf "\$s/\$/\033[m/")"
    fi

  elif [ -n "$GHOSTTY_BIN_DIR" ]; then
    if command -v kitten >/dev/null 2>&1; then
      kitten icat --clear --transfer-mode=memory --unicode-placeholder --stdin=no --place="$dim@0x0" "$file" | sed "\$d" | sed "$(printf "\$s/\$/\033[m/")"
    elif command -v icat >/dev/null 2>&1; then
      icat --clear --transfer-mode=memory --unicode-placeholder --stdin=no --place="$dim@0x0" "$file" | sed "\$d" | sed "$(printf "\$s/\$/\033[m/")"
    else
      chafa -s "$dim" "$file"
    fi
  elif command -v chafa >/dev/null 2>&1; then
    case "$CLI_PLATFORM" in
    android) chafa -s "$dim" "$file" ;;
    windows) chafa -f sixel -s "$dim" "$file" ;;
    *) chafa -s "$dim" "$file" ;;
    esac
    echo

  elif command -v imgcat >/dev/null; then
    imgcat -W "${dim%%x*}" -H "${dim##*x}" "$file"

  else
    printf "%s" "$TXT_PREVIEW_INSTALL_VIEWER"
  fi
}
EOF
  else
    return
  fi
}

# ==============================================================================
# State Management
# ==============================================================================
__state_clean_prev() {
  local current_state_dir
  current_state_dir="$CLI_CURRENT_STATE_DIR/$STATE_CURRENT"
  ! [ -d "$current_state_dir" ] && ui_notify_critical "$TXT_STATE_MALFORMED_CURRENT"
  rm -rf "$current_state_dir"
}

_state_init() {
  STATE_CURRENT=0
}

_state_push() {
  local current_state_dir

  STATE_CURRENT="$((STATE_CURRENT + 1))"
  current_state_dir="$CLI_CURRENT_STATE_DIR/$STATE_CURRENT"
  mkdir -p "$current_state_dir"

  cat <<EOF >"$current_state_dir/state.env"
# $CLI_APP_NAME state env file for state $STATE_CURRENT
EOF
}

_state_pop() {
  local current_state_dir
  local pop_count
  local i
  i=0
  pop_count="${1:-1}"

  [ "$pop_count" -le 0 ] && return

  while [ "$i" -lt "$pop_count" ]; do
    __state_clean_prev
    STATE_CURRENT="$((STATE_CURRENT - 1))"
    i=$((i + 1))
  done

  [ "$((STATE_CURRENT))" -lt 1 ] && return

  current_state_dir="$CLI_CURRENT_STATE_DIR/$STATE_CURRENT"
  ! [ -d "$current_state_dir" ] && ui_notify_critical "$TXT_STATE_MALFORMED_CURRENT"

  # shellcheck disable=SC1091
  . "$current_state_dir/state.env" || ui_notify_critical "$TXT_STATE_MALFORMED_CURRENT"
}
